#!/usr/bin/env bash
# Portions Copyright (c) 2005-2007  WyldRyde IRC Network
# Copyright (c) 2009 GeekShed Ltd.
# All rights reserved.
#
# $Id$
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.

for script in include/*
do
	. ${script}
done

conf_init

main () {
	# run through scripts
	for WORKINGSERVER in `grep ^S ${STRIPCONF}`
	do
		export WORKINGSERVER
		SERVERNAME=`echo ${WORKINGSERVER} | cut -f 2 -d :` ; export SERVERNAME
		REGION=`echo ${WORKINGSERVER} | cut -f 9 -d :` ; export REGION
		echo "${WORKINGSERVER}"
		echo "${SERVERNAME}"
		CONFPATH=${OUTPUTPATH}/conf/${SERVERNAME} ; export CONFPATH
		mkdir -p ${CONFPATH}
		for args in server links ports opers spamfilter
		do
				case ${args} in
					server) server_gen ;;
					links) links_gen ;;
					ports) ports_gen ;;
					opers) opers_gen ;;
					spamfilter) touch ${CONFPATH}/autospamfilter.conf ;;
				esac
		done
		cp -Rp ${SCRIPTROOT}/conf/${NETWORK}/global/* ${CONFPATH}
		cd ${CONFPATH} 
		tar -cvf - * | bzip2 | ossh ${SERVERNAME} "bunzip2 | tar -xf - -C ${NETSHORTNAME}-data/${NETSHORTNAME}-ircd/"
	done
}


main $*
rm -r ${OUTPUTPATH}
